name: Deploy
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
on: pull_request
jobs:
  Deploy-Storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: yarn install
      - name: Build storybook
        run: yarn build-storybook
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Publish site
        run: |
          aws s3 sync storybook-static s3://${{ secrets.S3_BUCKET }}/gh-${{ github.event.pull_request.id }} 